package actions

import (
	"fmt"
	"jarbas-go/main/model"
	"jarbas-go/main/vendors/openai"
)

type Answer struct {
	PreviousMessages []map[string]interface{}
	LastMessage      string
	// The "prompt_tokens" field represents the number of tokens in the prompt text that was provided with the request.
	// Tokens, in this sense, refer to individual words or pieces of text that have been separated by spaces or punctuation marks.
	PromptToken string
	// The "completion_tokens" field represents the number of tokens in the generated text that is returned in response to the request.
	// This indicates how many new words or sentences have been generated by the API beyond the original prompt text.
	CompletionToken string
	// The "total_tokens" field is the sum of prompt_tokens and completion_tokens, representing the total number of tokens involved in the request and response.
	TotalToken string
}

func validateResponse(response interface{}) (string, error) {
	if response == nil {
		return "", fmt.Errorf("response is nil")
	}

	if response == "" {
		return "", fmt.Errorf("response is empty")
	}

	if response.([]interface{})[0] == nil {
		return response.(string), fmt.Errorf("response is not the expected type")
	}

	return fmt.Sprint(response), nil
}

func Question(input string, settings model.Settings) (string, error) {
	// Define the request body as a JSON object
	body := map[string]interface{}{
		"model": settings.Model,
		"messages": []map[string]string{
			{"role": "user", "content": input},
		},
	}
	respData, err := openai.DoRequest(body, settings.ApiKey)
	if err != nil {
		return "", err
	}

	response, err := validateResponse(respData["choices"])
	if err != nil {
		return response, err
	}

	text := respData["choices"].([]interface{})[0].(map[string]interface{})["message"].(map[string]interface{})["content"].(string)

	return text, nil
}

func ChatQuestion(messages []map[string]interface{}, question string, settings model.Settings) (Answer, error) {
	newQuestion := map[string]interface{}{
		"role": "user", "content": question,
	}

	finalMessage := append(messages, newQuestion)

	// Define the request body as a JSON object
	body := map[string]interface{}{
		"model":    settings.Model,
		"messages": finalMessage,
	}
	respData, err := openai.DoRequest(body, settings.ApiKey)
	if err != nil {
		return Answer{}, err
	}

	lastMessage := respData["choices"].([]interface{})[0].(map[string]interface{})["message"].(map[string]interface{})["content"].(string)
	messagesRequest := respData["choices"].([]interface{})[0].(map[string]interface{})["message"].(map[string]interface{})

	promptTokens := respData["usage"].(map[string]interface{})["prompt_tokens"]
	completionTokens := respData["usage"].(map[string]interface{})["completion_tokens"]
	totalTokens := respData["usage"].(map[string]interface{})["total_tokens"]

	answer := Answer{
		PreviousMessages: append(finalMessage, messagesRequest),
		LastMessage:      lastMessage,
		PromptToken:      fmt.Sprint(promptTokens),
		CompletionToken:  fmt.Sprint(completionTokens),
		TotalToken:       fmt.Sprint(totalTokens),
	}

	return answer, nil
}
